# Generated by Django 5.2.6 on 2025-10-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="veiculos/fotos"),
        ),
    ]
