# Generated by Django 5.2.6 on 2025-10-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculo", "0002_veiculo_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="veiculo",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="veiculo/fotos"),
        ),
    ]
